name : Deploying NodeJS CRUD APP


on:
 push:
   branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - name : Checkout code
       uses : actions/checkout@v3


     - name : Deploy to server
       run : |
         ssh -i ${{SSH_PRIVATE_KEY}} ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
           cd /home/ubuntu/Continuous_Integeration_deployment
           git pull origin main
           npm install
           npm run build
           pm2 restart all
         EOF  