name : Deploying NodeJS CRUD APP


on:
 push:
   branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - name : Checkout code
       uses : actions/checkout@v3


     - name : setup SSH
       run : | 
         echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/ssh_key
         chmod 600 ~/ssh_key
         ssh-keyscan ${{secrets.SERVER_IP}} >> ~/.ssh/known_hosts

     - name : Deploy to server
       run : |
         ssh -i ~/ssh_key ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
           cd /home/ubuntu/Continuous_Integeration_deployment
           git pull origin main
           npm install
           npm run build
           pm2 restart all
         EOF  